// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('123', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('123', async function() {
    await driver.get("https://so.douyin.com/")
    await driver.manage().window().setRect(877, 1020)
    await driver.findElement(By.css(".input-EclX1G")).click()
    await driver.findElement(By.css(".sugItemWrapper-jclTJ3:nth-child(1) .sugTextWrapper-W6XkrX")).click()
    await driver.switchTo().frame(0)
    {
      const element = await driver.findElement(By.css(".tit:nth-child(2)"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".tit:nth-child(2)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css(".tit:nth-child(2)"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    {
      const element = await driver.findElement(By.css(".active > canvas"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".canvas-container:nth-child(8) > canvas"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css(".canvas-container:nth-child(8) > canvas"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.id("captcha_verify_image")).click()
    await driver.findElement(By.css(".vc-captcha-verify-pc-button")).click()
    {
      const element = await driver.findElement(By.css(".drager"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".drager"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css(".drager"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.id("captcha_verify_image")).click()
    await driver.findElement(By.css(".vc-captcha-verify-pc-button")).click()
    await driver.findElement(By.css(".verify-message-icon")).click()
    {
      const element = await driver.findElement(By.css(".active > canvas"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".canvas-container:nth-child(8) > canvas"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css(".canvas-container:nth-child(8) > canvas"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.id("captcha_verify_image")).click()
    await driver.findElement(By.css(".vc-captcha-verify-click-action")).click()
    await driver.findElement(By.css(".vc-captcha-verify-button-text")).click()
    await driver.findElement(By.css(".verify-message-tit")).click()
    {
      const element = await driver.findElement(By.css(".drager"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".drager"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css(".drager"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.id("captcha_verify_image")).click()
    await driver.findElement(By.css(".vc-captcha-verify-pc-button")).click()
    await driver.switchTo().defaultContent()
    await driver.findElement(By.css(".card-item:nth-child(9) .container_1f7ff:nth-child(1) > svg")).click()
    await driver.executeScript("window.scrollTo(0,5600)")
  })
})
