# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test323():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_323(self):
    self.driver.get("https://so-landing.douyin.com/landings/hotlist?board_type=0&enter_method=hot_mini_view&is_no_width_reload=0&app_theme=light&pd=general")
    self.driver.set_window_size(779, 614)
    self.driver.find_element(By.CSS_SELECTOR, ".TextPrimarylightbold").click()
    self.driver.find_element(By.CSS_SELECTOR, "#tab_1 .TextTertiarylight").click()
    self.driver.find_element(By.CSS_SELECTOR, "#tab_0 .TextTertiarylight").click()
    self.driver.find_element(By.CSS_SELECTOR, "#tab_2 .TextTertiarylight").click()
    self.driver.find_element(By.CSS_SELECTOR, "#tab_3 .TextTertiarylight").click()
    self.driver.find_element(By.CSS_SELECTOR, "#tab_4 .TextTertiarylight").click()
    self.driver.close()
  
